# Generated by Django 5.0 on 2024-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_kart', '0008_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_NO',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
