# Generated by Django 5.0 on 2024-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_kart', '0009_alter_address_mobile_no_alter_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_NO',
            field=models.IntegerField(max_length=10),
        ),
    ]
